### ISSUE TITLE
TLD & Pricing Sync Not working in 8.1.0

### ISSUE THREAD

**Issue by HerzGegenFame** [inwx/WHMCS#16]
The Domain and Pricing Sync is not working.

No matter if i disable 2 fa or not.

INWX is the only current registra configured.

I Tried it both with the release and with the current dev files from the repo.

Syncing:
![image](https://user-images.githubusercontent.com/50178021/105962161-be9ceb00-607f-11eb-8b9d-e76535c3f8d5.png)

Result:
![image](https://user-images.githubusercontent.com/50178021/105962218-cd839d80-607f-11eb-80ad-f727b02da7ed.png)

**Comment by NickUfer** [comment]
Hey, thanks for your report. This should be fixed now. If not please feel to write another comment 👍🏼
