### ISSUE TITLE
whmcs-8.1.post4 changes the registrar folder to inwx

### ISSUE THREAD

**Issue by howdytom** [inwx/WHMCS#19]
With whmcs-8.1.post4 the folder name has been changed from '_internetworx_' to '_inwx_'. Previous Domain Registrations are still using the old naming convention 'internetworx', though. When I try to replace the domain Registrar in the tbldomains SQL table the old Registrar 'internetworx' still shows up in the WHMCS  Registrar  dropdown menu. 

How do I completely replace old leftovers?

**Comment by howdytom** [comment]
Anyone?

**Comment by inwx-developer** [comment]
We have that issue in our backlog and will have a look at it soon.

**Comment by ddmler** [comment]
Sorry for the late reply.
Easiest solution would be to download 1 Version before that from GitHub and put the folder next to the inwx folder, then uninstall inside whmcs and remove the folder again. You may want to move all domains to a different registrar just to be sure while you do this.
