### ISSUE TITLE
The given parameter value for 'registrant' does not match the expected parameter type 'int'

### ISSUE THREAD

**Issue by rrothenburger** [inwx/WHMCS#20]
When trying to change the domain contact information in WHMCS, the following error is returned: The given parameter value for 'registrant' does not match the expected parameter type 'int'

Unfortunately, the data is not updated either.

**Comment by zoechi** [comment]
`The given parameter value for 'username' does not match the expected parameter type 'username'` when trying to create a user.
These error messages are really useless.
