### ISSUE TITLE
WHMCS 7.3 support

### ISSUE THREAD

**Issue by ArjonBu** [inwx/WHMCS#7]
Hello, 
Does your module work with WHMCS 7.3?

**Comment by enrikberisha** [comment]
@Arjoni Unfortunately not. @BaileyRud Are you able to get that fixed?

I'm getting just errors:

Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

Error: Call to undefined function xmlrpc_encode_request() in /var/www/whmcs/modules/registrars/internetworx/internetworxapi.php:37
Stack trace:
#0 /var/www/whmcs/modules/registrars/internetworx/internetworxapi.php(27): domrobot->call('account', 'login', Array)
#1 /var/www/whmcs/modules/registrars/internetworx/internetworxapi.php(15): domrobot->login('Novahosting', '!nova36745')
#2 /var/www/whmcs/modules/registrars/internetworx/internetworx.php(101): domrobot->__construct('Novahosting', '!nova36745', '')
#3 /var/www/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): internetworx_GetNameservers(Array)
#4 /var/www/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call('GetNameservers', Array)
#5 /var/www/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains.php(0): WHMCS\Module\Registrar->call('GetNameservers', '')
#6 /var/www/whmcs/aaa_admin/clientsdomains.php(0): WHMCS\Domains->moduleCall('GetNameservers')
#7 {main}

**Comment by ddmler** [comment]
We have released a new version which works with the current 7.9. It may also work with 7.3 still.
