### ISSUE TITLE
Domainsync

### ISSUE THREAD

**Issue by Tobi7889** [inwx/WHMCS#8]
Domainsync actually does not work on WHMCS 7.6.1 anyone have a way to get it work?

**Comment by konzeptplus-gmbh** [comment]
@inwx-developer 
Did you or someone test this on the latest whmcs 7.7? Thansk for your respond.

**Comment by Tobi7889** [comment]
> @inwx-developer
> Did you or someone test this on the latest whmcs 7.7? Thansk for your respond.

There is still the same problem ;)

**Comment by DerDanilo** [comment]
Awesome, no answer for like forever. So inwx doesn't seem to properly support their plugins. Hence it's kind of useless to use.

**Comment by ddmler** [comment]
Hi, currently this plugin does not support the 7.x branch of WHMCS. It only offers limited functionality for these versions. We are currently working on a new version of our plugin to fully support these newer versions. Unfortunately I cannot say yet how long this will take. Sorry.

**Comment by ddmler** [comment]
We have released a new version of our WHMCS plugin and tested the Domain sync feature with WHMCS 7.9. If you encounter any issues don't hesitate to contact our support. Thanks.
